### ISSUE TITLE
task: add targetcheck to Spicebot shared

### ISSUE THREAD

**Issue by josh-cunning** [SpiceBot/SpiceBot#1116]
https://github.com/deathbybandaid/SpiceBot/blob/dev/modules/Main/Duels.py#L292-L302

https://github.com/deathbybandaid/SpiceBot/blob/dev/modules/Main/Duels.py#L2900-L2946

https://github.com/deathbybandaid/SpiceBot/blob/dev/modules/Main/Duels.py#L416-L420

**Comment by josh-cunning** [comment]
replace/combine with old process:
botusersarray = get_botdatabase_value(bot, bot.nick, 'botusers') or []
botuseron=[]
	for u in bot.users:
		if u in botusersarray and u != bot.nick:
			botuseron.append(u)
elif not target.lower() in [u.lower() for u in botuseron]:

**Comment by josh-cunning** [comment]
function targetcheck added to spicebot shared. returns a number based on type of target. 
Duels has the option to check if a user is offline so still need to add that function

**Comment by josh-cunning** [comment]
Do we have a wiki on spicebot shared?

**Comment by Berserkir-Wolf** [comment]
Not as such yet.
Any code explanations at present are in developer guidelines.
If you'd like to put the explanations/examples/shared functions anywhere (I'm intending to later on), you can put them in [this page](https://github.com/deathbybandaid/SpiceBot/wiki/Shared-Functions) and I can tidy up wording of it later.

**Comment by josh-cunning** [comment]
I need change output to be text string instead of number system to avoid confusion  and need to add option to check offline database.

**Comment by josh-cunning** [comment]
Added offline option
