### ISSUE TITLE
Feature request: Add features to DJ to add songs

### ISSUE THREAD

**Issue by josh-cunning** [SpiceBot/SpiceBot#1206]
use the code in  https://github.com/deathbybandaid/SpiceBot/blob/dev/modules/Main/Fix.py to allow songs to be added. Charge $$$ spicebucks to add a song and $ to play a random song

**Comment by Berserkir-Wolf** [comment]
I like it.
At this rate we're going to need to make the project 'spicebucks' instead of 'casino'

**Comment by deathbybandaid** [comment]
feature done with new dict system
