### ISSUE TITLE
Add databases to to be searchable and with random option

### ISSUE THREAD

**Issue by josh-cunning** [SpiceBot/SpiceBot#2282]
Create a module to search  for quotes and similar things
confucius
Mark Twain quotes
futurama quotes
Amazon reviews
General quotes
User generated database of quotes/motto
jokes database user generated?
Youtube
Music Videos 
horoscopes
philosophical musings
today in history
movies
fortune cookie
luck numbers

**Comment by Berserkir-Wolf** [comment]
I'm partway through this in my own little notes.

I want the fortune cookie, yes, no, confucius to be a standard database function.
There used to be a quotes page at spice.dussed.com, but I've not seen dussed around in ages.

**Comment by josh-cunning** [comment]
I think we should make search.py more of a shared class with a basic template for search so we can easily add a new search function as soon as we find a website. We should also write a template class for the generated databases for the same reason
