### ISSUE TITLE
chan reports

### ISSUE THREAD

**Issue by deathbybandaid** [SpiceBot/SpiceBot#402]
this module needs to do the things

https://github.com/deathbybandaid/sopel-modules/blob/dev/Chan-Reporting.py

**Comment by deathbybandaid** [comment]
moved it to the Code-Scraps bin until we work on it

**Comment by deathbybandaid** [comment]
````
channel = bot.db.get_nick_value(nick, 'seen_channel')
message = bot.db.get_nick_value(nick, 'seen_message')
action = bot.db.get_nick_value(nick, 'seen_action')
````

These could be used to see if a user has been seen

````
inactiveusersarray = []
for u in bot.users:
    channel = bot.db.get_nick_value(nick, 'seen_channel')
    message = bot.db.get_nick_value(nick, 'seen_message')
    action = bot.db.get_nick_value(nick, 'seen_action')
    if not channel and not message and not action:
        inactiveusersarray.append(u)
````

**Comment by deathbybandaid** [comment]
just have to collect the data without being to intensive on the database

**Comment by deathbybandaid** [comment]
this one may need to wait for a better database, or possibly a seperate one

**Comment by Berserkir-Wolf** [comment]
What were you wanting this one to do?
Seen already collects it. I'm tempted to abstract seen to be like tell with a separate file, call it the UserStats module.

**Comment by deathbybandaid** [comment]
See stuff like who the chance lurkers are

**Comment by josh-cunning** [comment]
So this has been open forever. Did we do this? Do we still want to?
